name: gnome-dictionary
adopt-info: gnome-dictionary
summary: Check word definitions and spellings in an online dictionary
description: |
  GNOME Dictionary is a simple dictionary application that looks up
  definitions of words online.

  Though it looks up English definitions by default, you can easily switch to
  Spanish or add other online dictionaries using the DICT protocol to suit your
  needs.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  gnome-dictionary:
    interface: dbus
    bus: session
    name: org.gnome.Dictionary

apps:
  gnome-dictionary:
    command: usr/bin/gnome-dictionary
    extensions: [gnome-3-38]
    plugs:
      - network
    desktop: usr/share/applications/org.gnome.Dictionary.desktop

parts:
  gnome-dictionary:
    source: https://gitlab.gnome.org/GNOME/gnome-dictionary.git
    source-type: git
    source-tag: '40.0'
    plugin: meson
    meson-version: 0.58.1
    meson-parameters: [--prefix=/snap/gnome-dictionary/current/usr]
    organize:
      snap/gnome-dictionary/current/usr: usr
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
